helloworld_server.out: helloworld_server.o
	gcc -o helloworld_server.out helloworld_server.o

helloworld_client.out: helloworld_client.o
	gcc -o helloworld_client.out helloworld_client.o

helloworld_server.o: helloworld_server.c
	gcc -c -o helloworld_server.o helloworld_server.c

helloworld_client.o: helloworld_client.c
	gcc -c -o helloworld_client.o helloworld_client.c
